Repository 42rave/transcendence, pull requests merged in 2023-10, with the labels that each got.

#59 REWORK CHAT SERVICE:
  back/src/chat/channel/channel.service.ts
  back/src/chat/chat.gateway.ts
  back/src/chat/chat.service.ts
  back/src/types/server.d.ts
Labels: Rework

#62 ADD APP CONTROLLER (BACKEND):
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/config/app.config.ts
Labels: Feature

#57 MERGE PRODUCTION ENVIRONMENT:
  .env.dev.sample
  .env.sample
  .gitignore
  Makefile
  back/.dockerignore
  back/Dockerfile
  back/entrypoint.sh
  back/package.json
  back/src/config/auth.config.ts
  docker-compose.dev.yml
  docker-compose.yml
  front/.dockerignore
  front/Dockerfile
  front/components/chat/box.vue
  front/components/widget/totpEnable.vue
  front/entrypoint.sh
  front/nuxt.config.ts
  front/stores/auth.store.ts
  proxy/entrypoint-wrapper.sh
  proxy/templates/default.conf.template
Labels: Update, Feature

#55 MERGE WEBSOCKETS EVENTS (BACKEND):
  Makefile
  back/prisma/migrations/20230930082143_initial/migration.sql
  back/prisma/schema.prisma
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.service.ts
  back/src/chat/chat.module.ts
  back/src/chat/chat.service.ts
  back/src/chat/message/message.controller.spec.ts
  back/src/chat/message/message.controller.ts
  back/src/chat/message/message.service.spec.ts
  back/src/chat/message/message.service.ts
  back/src/chat/privmsg/privmsg.controller.spec.ts
  back/src/chat/privmsg/privmsg.controller.ts
  back/src/chat/privmsg/privmsg.service.spec.ts
  back/src/chat/privmsg/privmsg.service.ts
  back/src/guards/isNotBlocked.guard.ts
  back/src/guards/isNotMuted.guard.ts
  back/src/guards/isPrivmsg.guard.ts
  back/src/guards/isUserSocket.guard.ts
  back/src/types/channel.dto.ts
  back/src/types/message.dto.ts
Labels: Feature

#68 MERGE BETTER PROD / DEV ENV:
  .env.dev.sample
  .env.sample
  Makefile
  docker-compose.dev.yml
  docker-compose.yml
  front/Dockerfile
Labels: Update

#70 MERGE TRUSTED DEVICE:
  back/prisma/migrations/20231004101022_initial/migration.sql
  back/prisma/schema.prisma
  back/src/auth/auth.controller.ts
  back/src/auth/auth.module.ts
  back/src/auth/device/device.controller.ts
  back/src/auth/device/device.service.ts
  back/src/guards/totp.guard.ts
  back/src/middleware/totp.middleware.ts
Labels: Feature

#74 FIX JOIN CHANNEL:
  back/src/chat/channel/channel.service.ts
Labels: unexpected behaviour, Fix

#69 MERGE FETCH WRAPPER (FRONTEND):
  front/components/chat/box.vue
  front/components/widget/totpEnable.vue
  front/layouts/default.vue
  front/nuxt.config.ts
  front/plugins/api.plugin.ts
  front/plugins/auth.plugin.ts
  front/stores/auth.store.ts
Labels: Update, Feature

#76 REWORK REMOVE PAGINATION:
  back/src/app.module.ts
  back/src/auth/auth.controller.spec.ts
  back/src/auth/auth.service.spec.ts
  back/src/chat/channel/channel.controller.spec.ts
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.service.spec.ts
  back/src/chat/channel/channel.service.ts
  back/src/chat/chat.controller.spec.ts
  back/src/chat/chat.gateway.spec.ts
  back/src/chat/chat.service.spec.ts
  back/src/chat/message/message.controller.spec.ts
  back/src/chat/message/message.controller.ts
  back/src/chat/message/message.service.spec.ts
  back/src/chat/message/message.service.ts
  back/src/chat/privmsg/privmsg.controller.spec.ts
  back/src/chat/privmsg/privmsg.controller.ts
  back/src/chat/privmsg/privmsg.service.spec.ts
  back/src/chat/privmsg/privmsg.service.ts
  back/src/game/game.controller.spec.ts
  back/src/game/game.service.spec.ts
  back/src/middleware/pagination.middleware.spec.ts
  back/src/middleware/pagination.middleware.ts
  back/src/prisma/prisma.service.spec.ts
  back/src/relationship/relationship.controller.spec.ts
  back/src/relationship/relationship.service.spec.ts
  back/src/types/pagination.dto.ts
  back/src/types/request.d.ts
  back/src/user/user.controller.spec.ts
  back/src/user/user.controller.ts
  back/src/user/user.service.spec.ts
  back/src/user/user.service.ts
Labels: Rework

#78 FIX TOP RIGHT MENU (FRONTEND):
  front/components/layout/appBar.vue
Labels: unexpected behaviour, Fix

#77 ADD CUSTOM ERROR CALLBACK (FRONTEND):
  front/plugins/api.plugin.ts
  front/stores/auth.store.ts
Labels: Feature

#73 MERGE PASSWORD HASH && UNMETHODS:
  back/package.json
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.service.ts
Labels: Feature

#80 MERGE PROFILE PAGE:
  back/.gitignore
  back/package.json
  back/src/app.module.ts
  back/src/auth/auth.module.ts
  back/src/chat/chat.gateway.ts
  back/src/chat/chat.module.ts
  back/src/filters/serve-static.exception.ts
  back/src/main.ts
  back/src/types/user.dto.ts
  back/src/user/status/status.module.ts
  back/src/user/status/status.service.ts
  back/src/user/user.controller.ts
  back/src/user/user.module.ts
  back/src/user/user.service.ts
  front/components/layout/appBar.vue
  front/components/profile/avatar.vue
  front/components/profile/profile.vue
  front/components/profile/username.vue
  front/components/widget/settings.vue
  front/layouts/default.vue
  front/pages/profile/[id].vue
  front/pages/profile/index.vue
  front/plugins/api.plugin.ts
  front/stores/auth.store.ts
Labels: Feature

#81 MERGE CHATBOX AND CHATBAR (FRONT):
  back/src/chat/message/message.controller.ts
  back/src/guards/isNotMuted.guard.ts
  front/components/chat/bar.vue
  front/components/chat/box.vue
  front/components/chat/convDisplay.vue
  front/components/chat/creationForm.vue
  front/components/chat/menu.vue
  front/components/chat/messageInput.vue
  front/pages/chat.vue
  front/plugins/channel.plugin.ts
  front/plugins/chat.plugin.ts
  front/stores/channel.store.ts
  front/stores/chat.store.ts
  front/types/channel.ts
Labels: Feature

#84 MERGE FIX DEV (ENV):
  .env.dev.sample
  .env.sample
  docker-compose.dev.yml
Labels: unexpected behaviour, Fix

#85 MERGE RELATIONS FRONTEND:
  back/src/relationship/relationship.controller.ts
  back/src/relationship/relationship.module.ts
  back/src/relationship/relationship.service.ts
  back/src/user/status/status.service.ts
  front/components/chat/box.vue
  front/components/profile/profile.vue
  front/components/profile/relations.vue
  front/components/profile/social.vue
  front/stores/chat.store.ts
  front/types/relation.ts
Labels: Feature

#87 FIX SELF RELATIONSHIP:
  back/src/relationship/relationship.service.ts
Labels: Fix

#86 MERGE BETTER ALERT (FRONTEND):
  back/src/filters/serve-static.exception.ts
  front/components/chat/creationForm.vue
  front/components/layout/alert.vue
  front/components/profile/username.vue
  front/plugins/api.plugin.ts
Labels: Update, Feature

#89 ADD STATS (GAME):
  back/src/game/game.service.ts
Labels: Feature

#91 MERGE CHANNEL CREATION FIXES (CHAT):
  back/src/chat/channel/channel.service.ts
  back/src/types/channel.dto.ts
Labels: Fix

#93 MERGE LEFT RIGHT && FIX EVENTS (GAME / CHAT):
  back/prisma/migrations/20231007184051_initial/migration.sql
  back/prisma/schema.prisma
  back/src/chat/channel/channel.service.ts
  back/src/game/game.service.ts
Labels: Fix

#95 UPDATE FILTER MESSAGE OF BLOCKED USERS:
  back/src/chat/message/message.controller.ts
  back/src/chat/message/message.service.ts
Labels: Feature

#96 REWORK USER && SORTING LADDER && HISTORY:
  back/src/chat/chat.module.ts
  back/src/chat/message/message.service.ts
  back/src/game/game.service.ts
  back/src/user/user.controller.ts
  back/src/user/user.service.ts
Labels: Rework, Feature

#97 ADD MUTE TIME HANDLED FROM BACK:
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.service.ts
  back/src/game/game.service.ts
  back/src/types/channel.dto.ts
Labels: Feature

#98 MERGE CONVDISPLAY UPGRADE (FRONT):
  back/src/broadcast/broadcast.service.ts
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.service.ts
  back/src/chat/message/message.service.ts
  front/components/chat/actionMenu.vue
  front/components/chat/bar.vue
  front/components/chat/box.vue
  front/components/chat/convDisplay.vue
  front/components/chat/creationForm.vue
  front/components/chat/messageInput.vue
  front/components/layout/alert.vue
  front/plugins/chat.plugin.ts
  front/plugins/userChat.plugin.ts
  front/stores/channel.store.ts
  front/stores/userChat.store.ts
Labels: Feature

#103 MERGE PRIVMSG EVENTS:
  back/prisma/migrations/20231009165910_initial/migration.sql
  back/prisma/schema.prisma
  back/src/chat/channel/channel.service.ts
  back/src/chat/privmsg/privmsg.controller.ts
  back/src/chat/privmsg/privmsg.service.ts
Labels: Feature, Fix

#121 ADD RECONNECTION IN GAME:
  back/src/game/game.gateway.ts
  back/src/game/gameplay.service.ts
Labels: Feature

#126 ADD CUSTOM COLOR:
  front/components/game/play.vue
  front/components/widget/customColor.vue
  front/components/widget/settings.vue
Labels: Feature

#131 ADD SCORES AND GAME FINISHED:
  back/src/game/gameplay.service.ts
  front/components/game/finished.vue
  front/components/game/play.vue
  front/pages/game.vue
  front/types/game.ts
Labels: Feature

#137 ADD NAMES TO GAMEPLAY (BACK):
  back/src/game/gameplay.service.ts
  back/src/types/gameplay.ts
Labels: Feature

#138 ADD BETTER GAME WIN PAGE (FRONTEND):
  front/components/game/finished.vue
  front/pages/game.vue
  front/types/game.ts
Labels: Feature

#141 FIX GOAL RATIO:
  back/src/game/game.service.ts
Labels: Feature, Fix

#142 REWORK GAME PAGE (FRONTED):
  back/src/game/gameplay.service.ts
  front/components/game/play.vue
  front/pages/game.vue
  front/types/game.ts
Labels: Feature

#143 FIX CUSTOM COLOR COMPONENT (FRONTEND):
  front/components/widget/customColor.vue
Labels: unexpected behaviour, Fix
