Repository 42rave/transcendence, pull requests merged in 2023-09, with the labels that each got.

#28 MERGE IMPROVED AUTH WEBSOCKET AND CHAT:
  .env.sample
  back/package.json
  back/src/app.module.ts
  back/src/auth/auth.controller.ts
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.ts
  back/src/auth/guards/authenticated.guard.ts
  back/src/auth/strategies/fortyTwo.strategy.ts
  back/src/auth/strategies/jwt.strategy.ts
  back/src/chat/chat.controller.ts
  back/src/chat/chat.gateway.spec.ts
  back/src/chat/chat.gateway.ts
  back/src/chat/chat.module.ts
  back/src/chat/chat.service.ts
  back/src/prisma/prisma.service.ts
  back/src/types/request.d.ts
  back/src/types/socket.ts
  back/src/user/user.controller.ts
  back/src/user/user.module.ts
  back/src/user/user.service.ts
  back/tsconfig.json
  front/components/chat/box.vue
  front/layouts/default.vue
  front/nuxt.config.ts
  front/package-lock.json
  front/package.json
  front/pages/about.vue
  front/pages/chat.vue
  front/plugins/auth.plugin.ts
  front/plugins/mitt.plugin.ts
  front/plugins/vuetify.plugin.ts
  front/plugins/websockets.plugin.ts
  front/stores/auth.store.ts
  front/stores/auth.ts
  front/stores/websockets.store.ts
Labels: Rework, Feature

#19 MERGE UPDATED SCHEMA AND MIGRATION:
  .env.sample
  back/package.json
  back/prisma/migrations/20230910160101_init/migration.sql
  back/prisma/migrations/20230910172209_/migration.sql
  back/prisma/migrations/20230918123435_init/migration.sql
  back/prisma/schema.prisma
  front/stores/auth.ts
Labels: Update

#32 MERGE JOIN AND CREATE CHANNELS (CHAT):
  .gitignore
  back/prisma/migrations/20230918142707_fix_created_at/migration.sql
  back/prisma/schema.prisma
  back/src/chat/channel/channel.controller.spec.ts
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.module.ts
  back/src/chat/channel/channel.service.spec.ts
  back/src/chat/channel/channel.service.ts
  back/src/chat/chat.module.ts
  back/src/types/channel.dto.ts
Labels: Feature

#33 ADD PAGINATION MIDDLEWARE
  back/prisma/migrations/20230918153716_/migration.sql
  back/src/app.module.ts
  back/src/middleware/pagination.middleware.spec.ts
  back/src/middleware/pagination.middleware.ts
  back/src/types/pagination.dto.ts
  back/src/types/request.d.ts
  back/src/user/user.controller.ts
  back/src/user/user.service.ts
  back/tsconfig.json
Labels: Feature

#36 REWORK CHANNEL (BACKEND):
  back/prisma/migrations/20230918142707_fix_created_at/migration.sql
  back/prisma/migrations/20230920103042_initial/migration.sql
  back/prisma/schema.prisma
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.module.ts
  back/src/chat/channel/channel.service.ts
  back/src/chat/channel/message/message.controller.spec.ts
  back/src/chat/channel/message/message.controller.ts
  back/src/chat/channel/message/message.service.spec.ts
  back/src/chat/channel/message/message.service.ts
  back/src/chat/chat.module.ts
  back/src/guards/authenticated.guard.ts
  back/src/guards/isInChannel.guard.ts
  back/src/types/channel.dto.ts
  back/src/types/message.dto.ts
  back/tsconfig.json
Labels: Rework

#39 ADD MESSAGE CONTROLLER:
  back/src/chat/channel/channel.service.ts
  back/src/chat/channel/message/message.controller.ts
  back/src/chat/channel/message/message.service.ts
  back/src/chat/chat.controller.ts
  back/src/chat/chat.service.ts
  back/src/types/channel.dto.ts
  back/src/types/message.dto.ts
Labels: Feature

#41 UPDATE PRETTIER CONFIG:
  back/.prettierrc
  back/src/app.module.ts
  back/src/auth/auth.controller.spec.ts
  back/src/auth/auth.controller.ts
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.spec.ts
  back/src/auth/auth.service.ts
  back/src/auth/strategies/fortyTwo.strategy.ts
  back/src/auth/strategies/jwt.strategy.ts
  back/src/chat/channel/channel.controller.spec.ts
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.service.spec.ts
  back/src/chat/channel/channel.service.ts
  back/src/chat/channel/message/message.controller.spec.ts
  back/src/chat/channel/message/message.controller.ts
  back/src/chat/channel/message/message.service.spec.ts
  back/src/chat/channel/message/message.service.ts
  back/src/chat/chat.controller.spec.ts
  back/src/chat/chat.controller.ts
  back/src/chat/chat.gateway.spec.ts
  back/src/chat/chat.gateway.ts
  back/src/chat/chat.module.ts
  back/src/chat/chat.service.spec.ts
  back/src/chat/chat.service.ts
  back/src/config/api.config.ts
  back/src/config/auth.config.ts
  back/src/config/db.config.ts
  back/src/config/intra.config.ts
  back/src/game/game.controller.spec.ts
  back/src/game/game.controller.ts
  back/src/game/game.module.ts
  back/src/game/game.service.spec.ts
  back/src/guards/isInChannel.guard.ts
  back/src/main.ts
  back/src/middleware/pagination.middleware.spec.ts
  back/src/middleware/pagination.middleware.ts
  back/src/prisma/prisma.module.ts
  back/src/prisma/prisma.service.spec.ts
  back/src/prisma/prisma.service.ts
  back/src/types/channel.dto.ts
  back/src/types/message.dto.ts
  back/src/types/pagination.dto.ts
  back/src/types/request.d.ts
  back/src/types/socket.ts
  back/src/types/user.dto.ts
  back/src/user/user.controller.spec.ts
  back/src/user/user.controller.ts
  back/src/user/user.module.ts
  back/src/user/user.service.spec.ts
  back/src/user/user.service.ts
  back/test/app.e2e-spec.ts
Labels: Update, Workflow

#45 MERGE QUIT/KICK/INVITE/BAN (CHAT):
  back/.prettierrc
  back/prisma/migrations/20230921102024_initial/migration.sql
  back/prisma/schema.prisma
  back/src/chat/channel/channel.controller.ts
  back/src/chat/channel/channel.service.ts
Labels: Feature

#47 MERGE RELATIONSHIP:
  back/prisma/migrations/20230925072828_initial/migration.sql
  back/prisma/schema.prisma
  back/src/app.module.ts
  back/src/relationship/relationship.controller.spec.ts
  back/src/relationship/relationship.controller.ts
  back/src/relationship/relationship.module.ts
  back/src/relationship/relationship.service.spec.ts
  back/src/relationship/relationship.service.ts
Labels: Feature

#48 ADD 2FA WITH TOTP:
  back/package.json
  back/prisma/migrations/20230923233716_otp_table/migration.sql
  back/prisma/migrations/20230924174917_add_iv_field_on_otp_table/migration.sql
  back/prisma/schema.prisma
  back/src/app.module.ts
  back/src/auth/auth.controller.ts
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.ts
  back/src/auth/strategies/totp.strategy.ts
  back/src/config/auth.config.ts
  back/src/config/crypt.config.ts
  back/src/guards/authenticated.guard.ts
  back/src/guards/totp.guard.ts
  back/src/middleware/totp.middleware.ts
  back/src/types/request.d.ts
  back/src/types/user.dto.ts
  back/src/user/user.service.ts
  back/src/utils/crypt-manager.ts
  front/components/layout/appBar.vue
  front/components/widget/settings.vue
  front/components/widget/totpEnable.vue
  front/components/widget/totpLogin.vue
  front/components/widget/totpSettings.vue
  front/layouts/default.vue
  front/pages/settings.vue
  front/stores/auth.store.ts
  front/stores/auth.ts
  front/types/user.ts
Labels: Feature
